import { MainContainer } from '@/components/layout/main-container'
import './globals.scss'
import { AuthContextProvider } from '@/lib/context/auth-context'
import { ThemeContextProvider } from '@/lib/context/theme-context'
import { WindowContextProvider } from '@/lib/context/window-context'
import { Sidebar } from '@/components/sidebar/sidebar'
import { MobileFooter } from '@/components/sidebar/mobile-footer'
import { MobileHeader } from '@/components/sidebar/mobile-header'

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <WindowContextProvider>
            <ThemeContextProvider>
              <MainContainer>
                <Sidebar />
                <MobileHeader />
                {children}
                <MobileFooter />
              </MainContainer>
            </ThemeContextProvider>
          </WindowContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
