import { UserDataLayout } from '@/components/layout/user-data-layout';
import { UserHomeLayout } from '@/components/layout/user-home-layout';

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
}

export default function UserLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <UserDataLayout>
      <UserHomeLayout>
        {children}
      </UserHomeLayout>
    </UserDataLayout>
  );
}
