import { UserDataLayout } from '@/components/layout/user-data-layout';

export const metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
}

export default function UserLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <UserDataLayout>
      {children}
    </UserDataLayout>
  );
}
