import { Footer } from "@/components/layout/footer"

export const metadata = {
  title: 'Settings * Instagram',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col w-[70%] ml-0 xl:ml-20 items-center pt-5">
      <p className="mr-auto font-bold text-[25px] mb-5">Settings</p>
      {children}
      <div className="w-[55rem] ml-40 mt-5">
        <Footer />
      </div>
    </div>
  )
}
